# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeTestWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeTestWeather
  pod 'Alamofire'
  pod 'Nuke'
  pod 'DropDown'
  # UI
  pod 'MBProgressHUD', '0.9.2'
  
  target 'CodeTestWeatherTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire'
    pod 'Nuke'
    pod 'DropDown'
    # UI
    pod 'MBProgressHUD', '0.9.2'
  end

  target 'CodeTestWeatherUITests' do
    # Pods for testing
  end

end
